### ISSUE TITLE
[the node nvm doesn’t say installed. Once you close the terminal the node installation gets deleted. This is for the onboarding assignment a00]

### ISSUE THREAD

**Issue by vidyuthj** [comp426-2023-spring/a00#6] opened 2023-01-18 04:15 UTC
Please go through the following list and if you can answer "TRUE" to all of them, then create an issue:

1. [x] I searched the issues for any duplicate issues and didn't find anything.
2. [x] I do not think that this should be posted as a question in the discussions instead of as an issue.
3. [x] I attempted to figure out what is going on myself.

Did all of the above and still need help? Create an issue.
------------------------------------------------------------------

Refer to these articles to better understand how to effectively report an issue in GitHub:

https://medium.com/nyc-planning-digital/writing-a-proper-github-issue-97427d62a20f
https://github.com/codeforamerica/howto/blob/master/Good-GitHub-Issues.md
https://tilburgsciencehub.com/building-blocks/collaborate-and-share-your-work/project_management/write-good-issues/
https://rewind.com/blog/best-practices-for-using-github-issues/
https://ardalis.com/working-effectively-github-issues/
https://nira.com/common-github-issues/

Make sure to add **all the information needed to understand the issue** so that someone can help. 
If the info is missing we'll add the 'Needs more information' label and close the issue until there is enough information.

- [ ] Describe the issue.
- [ ] Provide screenshot.
- [ ] Provide a URL or link to the file where the issue is occurring.
- [ ] Describe how to reproduce the issue (What causes it to happen?)
- [ ] Provide a list of steps necessary to resolve the issue.

***Delete text above this line before you submit your issue. Place your issue information in the appropriate sections below.***

**Comment by jdmar3** [comment] 2023-01-24 21:35
So, the rubric above is there for you to fill out with information so we can actually help you. Please do that. Also, this is a duplicate of #3.

**Closed as completed by jdmar3** 2023-01-24 21:35 UTC
Labels: duplicate, help wanted, question
